# Generated by Django 5.0.3 on 2024-05-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.IntegerField(default='')),
                ('Task_Name', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
