# Generated by Django 5.0.3 on 2024-05-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Storager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Time',
            field=models.TimeField(default=''),
        ),
    ]
